// skills/nuxt-scaffold/scripts/templates/saas/app/pages/dashboard/index.vue
<script setup lang="ts">
definePageMeta({
  layout: false
})

useSeoMeta({
  title: 'Dashboard'
})

const { user, clear } = useUserSession()

async function onLogout() {
  await clear()
  await navigateTo('/')
}
</script>

<template>
  <div class="min-h-screen">
    <header class="border-b border-default flex items-center justify-between px-6 py-4">
      <AppLogo />
      <UButton
        label="Sign out"
        color="neutral"
        variant="ghost"
        icon="i-lucide-log-out"
        @click="onLogout"
      />
    </header>

    <UContainer class="py-12">
      <UPageCard
        title="Welcome back"
        :description="`Signed in as ${user?.email}`"
        icon="i-lucide-layout-dashboard"
      >
        <p class="text-muted">
          This is a private area — only reachable when logged in (see app/middleware/auth.global.ts).
          Auth here is a demo stand-in with no backend wired; swap server/api/login.post.ts and
          server/api/signup.post.ts for real calls before shipping.
        </p>
      </UPageCard>
    </UContainer>
  </div>
</template>

// skills/next-scaffold/scripts/templates/saas/src/app/dashboard/page.tsx
import { redirect } from 'next/navigation'
import { getSession } from '@/lib/session'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { LogoutButton } from './logout-button'

export default async function DashboardPage() {
  const session = await getSession()
  if (!session.user) redirect('/login')

  return (
    <div className="min-h-screen">
      <header className="flex items-center justify-between border-b px-6 py-4">
        <span className="font-semibold">{PROJECT_NAME}</span>
        <LogoutButton />
      </header>
      <div className="mx-auto max-w-2xl px-6 py-12">
        <Card>
          <CardHeader>
            <CardTitle>Welcome back</CardTitle>
            <CardDescription>Signed in as {session.user.email}</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              This is a private area — only reachable when logged in (see src/proxy.ts).
              Auth here is a demo stand-in with no backend wired; swap the /api/login and
              /api/signup routes for real calls before shipping.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
